remote_theme: galette/theme-ghpages
title: Galette HelloAsso
description: Plugin to handle membership fees and donations payments with HelloAsso
author: Guillaume AGNIERAY
maintainer: community
plugin:
  name: HelloAsso
  archive: galette-plugin-helloasso
  min_galette: "1.3.0"
defaults:
  - scope: {path: ""}
    values: {layout: default}
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
